# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
 repositories:
   - repository: buildapp
     type: github
     endpoint: giri347
     name: giri347/buildapp
   - repository: webappdeploy-AzureDevops
     type: github
     endpoint: giri347
     name: giri347/webappdeploy-AzureDevops
trigger:
- main


parameters:
  - name: select
    displayName: select_buildrepo
    values:
      - buildapp
      - webappdeploy-AzureDevops
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self


- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

